# Generated by Django 3.2.5 on 2022-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.IntegerField(choices=[(1, 'Production'), (2, 'UAT'), (3, 'Test')], verbose_name='Environment')),
                ('issue_class', models.IntegerField(choices=[(1, 'Bussines'), (2, 'Enhancement'), (3, 'Function'), (4, 'New Requirement')], verbose_name='Issue Class')),
                ('jira_id', models.CharField(max_length=150, verbose_name='Jira Name')),
                ('channel', models.IntegerField(choices=[(1, 'TOM'), (2, 'TOM-PCM'), (3, 'OBS'), (4, 'GATES'), (5, 'OLD-TOM'), (6, 'BLUE ADMIN'), (7, 'NONE')], verbose_name='Channel')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('issue_type', models.IntegerField(choices=[(1, 'Incident'), (2, 'Task')], verbose_name='Issue Type')),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'Major'), (3, ' Minor')], verbose_name='Priority')),
                ('status', models.IntegerField(choices=[(1, 'OPEN'), (2, 'ClOSED'), (3, 'IN PROGRESS'), (4, 'RESOLVED')], verbose_name='Status')),
                ('reporter', models.CharField(max_length=100, verbose_name='Reporter')),
                ('creator', models.CharField(max_length=100, verbose_name='Creator')),
                ('create', models.DateField(verbose_name='Create Date')),
                ('last_update', models.DateField(verbose_name='Last Update')),
                ('folder_id', models.IntegerField(verbose_name='Folder Id')),
                ('module', models.CharField(max_length=100, verbose_name='Module')),
                ('screen', models.CharField(max_length=100, verbose_name='Screen')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('description', models.TextField(verbose_name='Description')),
                ('last_comment', models.TextField(verbose_name='Last Comment')),
                ('affects_version', models.FloatField(verbose_name='Affects Version')),
                ('fix_version', models.FloatField(verbose_name='Fix Version')),
            ],
        ),
    ]
