# Generated by Django 3.2.5 on 2022-06-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
