# Generated by Django 3.2.5 on 2022-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20220619_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='channel',
            field=models.IntegerField(choices=[('TOM', 'TOM'), ('TOM-PCM', 'TOM-PCM'), ('OBS', 'OBS'), ('GATES', 'GATES'), ('OLD-TOM', 'OLD-TOM'), ('BLUE ADMIN', 'BLUE ADMIN'), ('NONE', 'NONE')], null=True, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='create',
            field=models.DateField(null=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creator',
            field=models.CharField(max_length=100, null=True, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='environment',
            field=models.IntegerField(choices=[('Production', 'Production'), ('UAT', 'UAT'), ('Test', 'Test')], null=True, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='folder_id',
            field=models.IntegerField(null=True, verbose_name='Folder Id'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_class',
            field=models.IntegerField(choices=[('Bussines', 'Bussines'), ('Enhancement', 'Enhancement'), ('Function', 'Function'), ('Requirement', 'New Requirement')], null=True, verbose_name='Issue Class'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(choices=[('Incident', 'Incident'), ('Task', 'Task')], null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='jira_id',
            field=models.CharField(max_length=150, null=True, verbose_name='Jira Id'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='last_update',
            field=models.DateField(null=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.CharField(max_length=100, null=True, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.CharField(max_length=100, null=True, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[('OPEN', 'OPEN'), ('ClOSED', 'ClOSED'), ('IN PROGRESS', 'IN PROGRESS'), ('RESOLVED', 'RESOLVED')], null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
