# Generated by Django 3.2.5 on 2022-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20220619_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='affects_version',
            field=models.FloatField(blank=True, null=True, verbose_name='Affects Version'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='channel',
            field=models.IntegerField(blank=True, choices=[('TOM', 'TOM'), ('TOM-PCM', 'TOM-PCM'), ('OBS', 'OBS'), ('GATES', 'GATES'), ('OLD-TOM', 'OLD-TOM'), ('BLUE ADMIN', 'BLUE ADMIN'), ('NONE', 'NONE')], null=True, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='environment',
            field=models.IntegerField(blank=True, choices=[('production', 'production'), ('UAT', 'UAT'), ('Test', 'Test')], null=True, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='fix_version',
            field=models.FloatField(blank=True, null=True, verbose_name='Fix Version'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='folder_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folder Id'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_class',
            field=models.IntegerField(blank=True, choices=[('Bussines', 'Bussines'), ('Enhancement', 'Enhancement'), ('Function', 'Function'), ('Requirement', 'New Requirement')], null=True, verbose_name='Issue Class'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(blank=True, choices=[('Incident', 'Incident'), ('Task', 'Task')], null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='jira_id',
            field=models.CharField(default=1, max_length=150, verbose_name='Jira Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='last_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Last Comment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='last_update',
            field=models.DateField(blank=True, null=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(blank=True, choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='screen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Screen'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(blank=True, choices=[('OPEN', 'OPEN'), ('ClOSED', 'ClOSED'), ('IN PROGRESS', 'IN PROGRESS'), ('RESOLVED', 'RESOLVED')], null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
