# Generated by Django 3.2.5 on 2022-06-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20220619_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='environment',
            field=models.IntegerField(blank=True, choices=[(1, 'production'), (2, 'UAT'), (3, 'Test')], null=True, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Issue Class'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Incident'), (2, 'Task')], null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Critical'), (2, 'Major'), (3, 'Minor')], null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'OPEN'), (2, 'ClOSED'), (3, 'IN PROGRESS'), (4, 'RESOLVED')], null=True, verbose_name='Status'),
        ),
    ]
