# Generated by Django 3.2.5 on 2022-06-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20220619_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('patronymic_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patronymic Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('gander', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='Gander')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='Active')),
                ('groups', models.TextField(blank=True, null=True, verbose_name='Groups')),
                ('merchant_login', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marchent')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='User')),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Incident'), (2, 'Task'), (3, 'Problem')], null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Critical'), (2, 'Major'), (3, 'Minor'), (4, 'High'), (5, 'Average'), (6, 'Medium')], null=True, verbose_name='Priority'),
        ),
    ]
