# Generated by Django 3.2.5 on 2022-06-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0002_auto_20220620_1435'),
        ('Core', '0007_auto_20220619_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.environment', verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.issueclass', verbose_name='Issue Class'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.issuetype', verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.priroty', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.status', verbose_name='Status'),
        ),
    ]
