# Generated by Django 3.2.5 on 2022-07-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0004_alter_station_station_type'),
        ('Core', '0009_auto_20220626_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='file',
        ),
        migrations.AlterField(
            model_name='issue',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(default=None, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(default=None, max_length=200, verbose_name='Title'),
        ),
    ]
