# Generated by Django 3.2.5 on 2022-07-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0004_alter_station_station_type'),
        ('Core', '0010_auto_20220717_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
