# Generated by Django 3.2.5 on 2022-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20220717_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Update'),
        ),
    ]
