# Generated by Django 3.2.5 on 2022-08-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20220821_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='last_comment',
        ),
    ]
