# Generated by Django 3.2.5 on 2022-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_auto_20220823_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='subscription_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='subscription_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sunscription Number'),
        ),
        migrations.AddField(
            model_name='issue',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subscription Type'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
