# Generated by Django 3.2.5 on 2022-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_auto_20220823_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='trans_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='M#'),
        ),
    ]
