# Generated by Django 3.2.5 on 2022-09-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_auto_20220824_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='follwer',
            new_name='assignee',
        ),
    ]
