# Generated by Django 3.2.5 on 2022-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_issue_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='window',
        ),
        migrations.AddField(
            model_name='issue',
            name='trip_date',
            field=models.DateField(blank=True, null=True, verbose_name='Trip Date'),
        ),
    ]
