# Generated by Django 3.2.5 on 2022-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station Name')),
                ('office_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Office Name')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number')),
            ],
        ),
    ]
