# Generated by Django 3.2.5 on 2022-06-21 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0004_alter_station_station_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ONSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSiteIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('supscription_type', models.CharField(max_length=50, verbose_name='Supscription Type')),
                ('affects_version', models.FloatField(verbose_name='Affects Version')),
                ('train', models.CharField(blank=True, max_length=50, null=True, verbose_name='Train')),
                ('attached', models.FileField(upload_to='', verbose_name='Attached File')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.channel', verbose_name='Device Type')),
                ('device_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ONSite.device', verbose_name='Device Serial')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.issuetype', verbose_name='Issue Type')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.module', verbose_name='Module')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMedule.priroty', verbose_name='Priority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
