# Generated by Django 3.2.5 on 2022-06-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONSite', '0002_onsiteissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onsiteissue',
            old_name='attached',
            new_name='file',
        ),
    ]
