# Generated by Django 3.2.5 on 2022-06-22 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminMedule', '0004_alter_station_station_type'),
        ('ONSite', '0003_rename_attached_onsiteissue_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnSiteIssue',
            new_name='OnSite',
        ),
    ]
