# Generated by Django 3.2.5 on 2022-06-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONSite', '0004_rename_onsiteissue_onsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsite',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='onsite',
            name='device_serial',
        ),
        migrations.RemoveField(
            model_name='onsite',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='onsite',
            name='module',
        ),
        migrations.RemoveField(
            model_name='onsite',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='onsite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='OnSite',
        ),
    ]
