# Generated by Django 3.2.5 on 2022-06-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0009_auto_20220626_1711'),
        ('ONSite', '0005_auto_20220626_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Files Name')),
                ('files', models.FileField(upload_to='files/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.issue', verbose_name='issue')),
            ],
        ),
    ]
