# Generated by Django 3.2.5 on 2022-07-17 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONSite', '0006_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
