# Generated by Django 3.2.5 on 2022-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONSite', '0007_files_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Files Name'),
        ),
    ]
