# Generated by Django 3.2.5 on 2022-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=50, verbose_name='Merchant')),
                ('deviceNum', models.CharField(blank=True, max_length=50, null=True, verbose_name='DeviceNum')),
                ('station', models.IntegerField(verbose_name='Station Code')),
                ('stationName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station Name')),
                ('officeEn', models.CharField(blank=True, max_length=50, null=True, verbose_name='OfficeEn')),
                ('officeAr', models.CharField(blank=True, max_length=50, null=True, verbose_name='OfficeAr')),
                ('window', models.IntegerField(blank=True, null=True, verbose_name='Window')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
            ],
        ),
    ]
