# Generated by Django 3.2.5 on 2022-07-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tom',
            name='merchant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='tom',
            name='station',
            field=models.IntegerField(blank=True, null=True, verbose_name='Station Code'),
        ),
        migrations.AlterField(
            model_name='tom',
            name='window',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Window'),
        ),
    ]
