# Generated by Django 3.2.5 on 2022-06-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0002_auto_20220620_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(max_length=100, verbose_name='station_type')),
                ('english_name', models.CharField(max_length=100, verbose_name='English Name')),
                ('arabic_name', models.CharField(max_length=100, verbose_name='Arabic Name')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('merchant_name', models.CharField(max_length=100, verbose_name='Merchant Name')),
            ],
        ),
    ]
