# Generated by Django 3.2.5 on 2022-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0003_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(max_length=100, verbose_name='Station Type'),
        ),
    ]
