# Generated by Django 3.2.5 on 2022-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0004_alter_station_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Class'),
        ),
    ]
