# Generated by Django 3.2.5 on 2022-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0005_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
    ]
