# Generated by Django 3.2.5 on 2022-09-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0007_alter_station_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='priroty',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='priroty',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='priroty',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
    ]
