# Generated by Django 3.2.5 on 2022-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0009_alter_priroty_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='weight'),
        ),
    ]
