# Generated by Django 3.2.5 on 2022-09-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0010_status_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='name_ar')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name_ar')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_offices', to='AdminMedule.station', verbose_name='station')),
            ],
        ),
    ]
