# Generated by Django 3.2.5 on 2022-09-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0011_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
