# Generated by Django 3.2.5 on 2022-09-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMedule', '0012_delete_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='arabic_name',
            field=models.CharField(max_length=20, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='english_name',
            field=models.CharField(max_length=20, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(max_length=20, verbose_name='Station Type'),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(blank=True, max_length=50, null=True, verbose_name='English Name')),
                ('nameAr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Arabic Name')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_office', to='AdminMedule.station', verbose_name='Station')),
            ],
        ),
    ]
