# Generated by Django 3.2.5 on 2022-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='avater/'),
        ),
    ]
